run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
    - errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-dirs:
    - internal/server # Temporarily skip until Gin is integrated
