/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autentica usuário
         * @description Autentica um usuário existente com e-mail e senha.
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atualiza tokens de acesso
         * @description Renova tokens baseando-se no refresh token válido.
         */
        post: operations["refreshAuthTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria empresa e usuário administrador
         * @description Fluxo inicial da plataforma: cria empresa, usuário admin e retorna tokens.
         */
        post: operations["signupCompanyAndUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista agendamentos
         * @description Lista agendamentos com filtros de data, status ou profissional.
         */
        get: operations["listBookings"];
        put?: never;
        /**
         * Cria agendamento
         * @description Cria um novo agendamento com profissional, serviço e data.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualiza agendamento
         * @description Atualiza os campos editáveis de um agendamento existente.
         */
        patch: operations["updateBooking"];
        trace?: never;
    };
    "/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela agendamento
         * @description Cancela um agendamento existente e registra o motivo.
         */
        post: operations["cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista clientes
         * @description Lista clientes com filtros de busca e paginação.
         */
        get: operations["listClients"];
        put?: never;
        /**
         * Cria cliente
         * @description Cria um cliente novo para o tenant com os dados fornecidos.
         */
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca cliente
         * @description Retorna os dados do cliente informado pelo ID.
         */
        get: operations["getClient"];
        /**
         * Atualiza cliente
         * @description Atualiza completamente o cliente informado pelo ID.
         */
        put: operations["updateClient"];
        post?: never;
        /**
         * Remove cliente
         * @description Remove (soft delete) o cliente especificado.
         */
        delete: operations["deleteClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retorna dados da empresa atual
         * @description Retorna as informações da empresa associada ao tenant autenticado.
         */
        get: operations["getCurrentCompany"];
        /**
         * Atualiza dados da empresa atual
         * @description Atualiza os campos configuráveis da empresa do tenant atual.
         */
        put: operations["updateCurrentCompany"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * KPIs diários
         * @description Retorna indicadores diários filtrados por data e profissional.
         */
        get: operations["getDailyDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista movimentações de estoque
         * @description Lista movimentações de estoque com filtros por produto, tipo e datas.
         */
        get: operations["listInventoryMovements"];
        put?: never;
        /**
         * Registra movimento de estoque
         * @description Registra uma movimentação de estoque (entrada, saída ou ajuste).
         */
        post: operations["createInventoryMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista pagamentos
         * @description Lista pagamentos processados com filtros por método e datas.
         */
        get: operations["listPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista produtos
         * @description Lista produtos cadastrados com paginação padrão.
         */
        get: operations["listProducts"];
        put?: never;
        /**
         * Cria produto
         * @description Cria um produto novo com preço, estoque e metadata.
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca produto por ID
         * @description Retorna o produto completo identificado pelo ID.
         */
        get: operations["getProduct"];
        /**
         * Atualiza produto
         * @description Atualiza os dados do produto informado.
         */
        put: operations["updateProduct"];
        post?: never;
        /**
         * Remove produto
         * @description Remove o produto indicado pelo ID.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/professionals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista profissionais ativos
         * @description Lista os profissionais ativos associados ao tenant.
         */
        get: operations["listProfessionals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista pedidos/vendas
         * @description Lista pedidos e vendas filtrando por status, cliente ou data.
         */
        get: operations["listSalesOrders"];
        put?: never;
        /**
         * Cria pedido/venda
         * @description Cria um pedido ou venda com itens e consumidor vinculados.
         */
        post: operations["createSalesOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualiza pedido
         * @description Atualiza campos editáveis de um pedido existente.
         */
        patch: operations["updateSalesOrder"];
        trace?: never;
    };
    "/sales/orders/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra pagamento
         * @description Registra um pagamento para o pedido informado.
         */
        post: operations["createSalesOrderPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista serviços
         * @description Retorna a lista completa de serviços configurados para o tenant.
         */
        get: operations["listServices"];
        put?: never;
        /**
         * Cria serviço
         * @description Cria um novo serviço associado ao tenant.
         */
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca serviço por ID
         * @description Busca os dados completos do serviço informado.
         */
        get: operations["getService"];
        /**
         * Atualiza serviço
         * @description Substitui os dados do serviço informado pelo payload.
         */
        put: operations["updateService"];
        post?: never;
        /**
         * Remove serviço
         * @description Remove (soft delete) o serviço informado pelo ID.
         */
        delete: operations["deleteService"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista usuários do tenant
         * @description Lista usuários do tenant com filtros e paginação.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Cria um usuário
         * @description Cria um novo usuário associado ao tenant.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca usuário por ID
         * @description Retorna os dados completos do usuário selecionado.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /**
         * Remove (soft delete) um usuário
         * @description Desativa o usuário informado sem apagar seu histórico.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /**
         * Atualiza parcialmente um usuário
         * @description Atualiza somente os campos informados para o usuário.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "handler.BookingCancelRequest": {
            reason?: string;
        };
        "handler.BookingRequest": {
            client_id: string;
            end_at?: string;
            notes?: string;
            professional_id: string;
            service_id: string;
            start_at: string;
            status?: string;
        };
        "handler.BookingUpdateRequest": {
            end_at?: string;
            notes?: string;
            start_at?: string;
            status?: string;
        };
        "handler.ClientRequest": {
            contact?: {
                [key: string]: unknown;
            };
            email?: string;
            name: string;
            notes?: string;
            phone?: string;
            tags?: string[];
        };
        "handler.CompanyUpdateRequest": {
            email?: string;
            name?: string;
            phone?: string;
            settings?: {
                [key: string]: unknown;
            };
            timezone?: string;
        };
        "handler.CreateUserRequest": {
            email: string;
            name: string;
            password: string;
            phone?: string;
            role: string;
        };
        "handler.InventoryRequest": {
            order_id?: string;
            product_id: string;
            quantity: number;
            reason?: string;
            type: string;
        };
        "handler.LoginRequest": {
            email: string;
            password: string;
        };
        "handler.PaymentRequest": {
            amount: number;
            details?: {
                [key: string]: unknown;
            };
            method: string;
            paid_at: string;
        };
        "handler.ProductRequest": {
            cost?: number;
            description?: string;
            metadata?: {
                [key: string]: unknown;
            };
            min_stock?: number;
            name: string;
            price: number;
            sku: string;
            stock_qty?: number;
        };
        "handler.RefreshRequest": {
            refresh_token: string;
        };
        "handler.SalesOrderItemRequest": {
            quantity: number;
            ref_id: string;
            type: string;
            unit_price: number;
        };
        "handler.SalesOrderRequest": {
            booking_id?: string;
            client_id: string;
            discount?: number;
            items: components["schemas"]["handler.SalesOrderItemRequest"][];
            notes?: string;
        };
        "handler.SalesOrderUpdateRequest": {
            notes?: string;
            status?: string;
        };
        "handler.ServiceRequest": {
            category?: string;
            color?: string;
            description?: string;
            duration_minutes: number;
            metadata?: {
                [key: string]: unknown;
            };
            name: string;
            price: number;
        };
        "handler.SignupRequest": {
            company: {
                document?: string;
                name: string;
                phone?: string;
            };
            user: {
                email: string;
                name: string;
                password: string;
                phone?: string;
            };
        };
        "handler.UpdateUserRequest": {
            active?: boolean;
            name?: string;
            password?: string;
            phone?: string;
            role?: string;
        };
        "response.APIResponse": {
            data?: unknown;
            error?: unknown;
            meta?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Cliente */
        "handler.ClientRequest": {
            content: {
                "application/json": components["schemas"]["handler.ClientRequest"];
            };
        };
        /** @description Produto */
        "handler.ProductRequest": {
            content: {
                "application/json": components["schemas"]["handler.ProductRequest"];
            };
        };
        /** @description Serviço */
        "handler.ServiceRequest": {
            content: {
                "application/json": components["schemas"]["handler.ServiceRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Credenciais */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    refreshAuthTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Refresh token */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    signupCompanyAndUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Dados do signup */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.SignupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    listBookings: {
        parameters: {
            query?: {
                /** @description Data (YYYY-MM-DD) */
                date?: string;
                /** @description Profissional */
                professional_id?: string;
                /** @description Status */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Agendamento */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.BookingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    updateBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description Campos editáveis */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.BookingUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Booking ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description Motivo */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.BookingCancelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    listClients: {
        parameters: {
            query?: {
                /** @description Filtro por nome/email/telefone */
                search?: string;
                /** @description Lista de tags separadas por vírgula */
                tags?: string;
                /** @description Página */
                page?: number;
                /** @description Itens por página */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["handler.ClientRequest"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    getClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Client ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Client ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["handler.ClientRequest"];
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    deleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Client ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    updateCurrentCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Campos editáveis */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.CompanyUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    getDailyDashboard: {
        parameters: {
            query?: {
                /** @description Data (YYYY-MM-DD) */
                date?: string;
                /** @description Profissional */
                professional_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    listInventoryMovements: {
        parameters: {
            query?: {
                /** @description Filtro por produto */
                product_id?: string;
                /** @description Tipo (in|out|adjustment) */
                type?: string;
                /** @description Data inicial (RFC3339) */
                start_date?: string;
                /** @description Data final (RFC3339) */
                end_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createInventoryMovement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Movimentação */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.InventoryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    listPayments: {
        parameters: {
            query?: {
                /** @description Método */
                method?: string;
                /** @description Data inicial RFC3339 */
                start_date?: string;
                /** @description Data final RFC3339 */
                end_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["handler.ProductRequest"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Product ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Product ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["handler.ProductRequest"];
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Product ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProfessionals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    listSalesOrders: {
        parameters: {
            query?: {
                /** @description Status */
                status?: string;
                /** @description Cliente */
                client_id?: string;
                /** @description Data (YYYY-MM-DD) */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createSalesOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pedido */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.SalesOrderRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    updateSalesOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Order ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description Campos editáveis */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.SalesOrderUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createSalesOrderPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Order ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description Pagamento */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.PaymentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    listServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["handler.ServiceRequest"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    getService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Service ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    updateService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Service ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["handler.ServiceRequest"];
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    deleteService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Service ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Filtro por role */
                role?: string;
                /** @description Página */
                page?: number;
                /** @description Itens por página */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Novo usuário */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description User ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description User ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description User ID
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description Campos editáveis */
        requestBody: {
            content: {
                "application/json": components["schemas"]["handler.UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.APIResponse"];
                };
            };
        };
    };
}
